### ISSUE TITLE
Restructure to be runnable as a GitHub action

### ISSUE THREAD

**Issue by delroth** [nix-community/label-approved#11]
There are several drawbacks to the current "crawling" approach used by this tool:
- Easily runs into quota issues
- Can't process more than the last 1K PRs by ID (due to GH search API limitations, maybe?)
- High latency since the whole set of open PRs needs to be recrawled on every run

I suggest the following complementary mode of operation:
- Add a mode to run only on one PR, whose ID is provided on the command line.
- Add all the scaffolding to be able to run this tool as a GitHub action.
- Register this action to run on PR review events on nixpkgs.

Happy to take care of this myself (want to share commit privileges / future maintenance? :p), I really just want this to finally happen automatically on nixpkgs.

**Comment by Artturin** [comment]
I added you as as collaborator with maintainer level permissions

**Comment by delroth** [comment]
Thanks! Do you still want to review those changes or are you giving me the green light to commit straight to master / self-merge?

**Comment by Artturin** [comment]
You can self merge

A few things to keep in mind

The program should stay runnable without the action
And it should eventually be runnable on non-nixpkgs repos

**Comment by delroth** [comment]
Pushed everything needed so this can be used as nix-community/label-approved@v1 in GH actions. https://github.com/NixOS/nixpkgs/pull/264633 is the nixpkgs side of things to start using this action, then I can stop running the bot :)
